class Data {
    /**
     * elided id => autogenerated id
     */
    id: string;

    constructor(id: string){
        this.id = id;
    }
}

export class DataElemento extends Data{
    nombre: string;

    constructor(id: string, nombre: string) {
        super(id);
        this.nombre = nombre;
    }
}

export class DataGrupo extends DataElemento {
    parent?: string;
    esGrupo?: boolean = false;

    constructor(id: string, nombre: string, parent?: string) {
        super(id, nombre);
        this.parent = parent;
    }
}

export class DataNodo extends DataElemento{
    urlFoto: string;
    nombreCreador: string;
    parent?: string;
    constructor(id: string, nombre: string, urlFoto: string, nombreCreador: string, parent?: string) {
        super(id, nombre);
        this.urlFoto = urlFoto;
        this.nombreCreador = nombreCreador;
        this.parent = parent;
    }
}

export class DataEdge extends Data {
    /**
     * the source node id (edge comes from this node)
     */
    source: string;
    /**
     * the target node id (edge goes to this node)
     */
    target: string;

    constructor(id: string, source: string, target: string) {
        super(id);
        this.source = source;
        this.target = target;
    }

}
